server:
  servlet:
    context-path: /vskendo
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTest?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Y38GnG9LXt0jp26B
    hikari:
      maximum-pool-size: 50
      max-lifetime: 18000
  redis:
    database: 3
    port: 6379
    host: localhost
